# Generated by Django 4.2.5 on 2023-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='sportec/images')),
                ('about', models.TextField(default='')),
                ('leader1', models.CharField(default='', max_length=100)),
                ('leader2', models.CharField(default='', max_length=100)),
                ('subleader1', models.CharField(default='', max_length=100)),
                ('subleader2', models.CharField(default='', max_length=100)),
                ('subleader3', models.CharField(default='', max_length=100)),
                ('past_events', models.TextField(default='')),
                ('upcoming_event', models.CharField(default='', max_length=500)),
                ('instagram_handle', models.URLField(default='', max_length=500)),
                ('facebook_handle', models.URLField(default='', max_length=500)),
                ('youtube_handle', models.URLField(default='', max_length=500)),
                ('linkedin', models.URLField(default='', max_length=500)),
                ('email', models.EmailField(default='', max_length=100)),
                ('suggestion_box', models.TextField(default='')),
                ('tagline', models.TextField(default='')),
                ('logo', models.ImageField(default='', upload_to='sportec/images')),
            ],
        ),
    ]
