# Generated by Django 4.2.5 on 2023-10-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildbeats', '0003_alter_subclub_email_alter_subclub_facebook_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclub',
            name='image',
            field=models.ImageField(default='', upload_to='wildbeats/images'),
        ),
    ]
