# Generated by Django 4.2.5 on 2023-11-05 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trendles', '0005_chitrachayaimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(help_text='Title of the document', max_length=255)),
                ('document', models.FileField(help_text='Upload a document (JPG, JPEG, PNG, PDF, Word)', upload_to='literary_club/documents/')),
                ('time_of_upload', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('subclub_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('majorclub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Literary Document',
                'verbose_name_plural': 'Literary Documents',
            },
        ),
    ]
