# Generated by Django 4.2.5 on 2023-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendles', '0006_literarydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literarydocument',
            name='document',
            field=models.FileField(blank=True, default='trendles/literaryclubdocs/default.txt', help_text='Upload a document (JPG, JPEG, PNG, PDF, Word)', null=True, upload_to='trendles/literaryclubdocs/'),
        ),
        migrations.AlterField(
            model_name='literarydocument',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
