# Generated by Django 4.2.5 on 2023-11-05 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trendles', '0007_alter_literarydocument_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingOutreachClubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='trendles/marketting/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subclub_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('majorclub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing & Outreach Club File',
                'verbose_name_plural': 'Marketing & Outreach Club Files',
            },
        ),
        migrations.CreateModel(
            name='FinanceClubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='trendles/financefile/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subclub_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('majorclub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Club File',
                'verbose_name_plural': 'Finance Club Files',
            },
        ),
        migrations.CreateModel(
            name='DesignClubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='trendles/designclubfile/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subclub_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('majorclub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Club File',
                'verbose_name_plural': 'Design Club Files',
            },
        ),
    ]
