# Generated by Django 4.2.5 on 2023-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendles', '0009_alter_chitrachayaimages_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitrachayaimages',
            name='media_file',
            field=models.FileField(blank=True, default='/media/trendles/images/unknown.png', help_text='Upload an image file.', null=True, upload_to='trendles/images'),
        ),
    ]
