# Generated by Django 4.2.5 on 2023-11-07 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trendles', '0010_alter_chitrachayaimages_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitrachayaimages',
            name='media_file',
            field=models.FileField(blank=True, default='/media/trendles/images/unknown.png', help_text='Upload an image file.', null=True, upload_to='trendles/images/'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
