# Generated by Django 4.2.5 on 2023-10-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='Home/images')),
                ('about', models.TextField(default='')),
                ('leader1', models.CharField(default='', max_length=100)),
                ('leader2', models.CharField(default='', max_length=100)),
                ('past_events', models.TextField(default='', null=True)),
                ('upcoming_event', models.CharField(default='', max_length=500, null=True)),
                ('instagram_handle', models.URLField(default='', max_length=500, null=True)),
                ('facebook_handle', models.URLField(default='', max_length=500, null=True)),
                ('youtube_handle', models.URLField(default='', max_length=500, null=True)),
                ('linkedin', models.URLField(default='', max_length=500, null=True)),
                ('email', models.EmailField(default='', max_length=100, null=True)),
                ('suggestion_box', models.TextField(default='', null=True)),
                ('tagline', models.TextField(default='', null=True)),
                ('logo', models.ImageField(default='', upload_to='Home/images')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('major_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.majorclub')),
            ],
        ),
    ]
