# Generated by Django 4.2.5 on 2023-10-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='exact_subclub_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
