# Generated by Django 4.2.5 on 2023-11-03 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_suggestion_exact_subclub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, default=datetime.date.today, help_text='Date of the event', null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('event_link', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('venue', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bySubClub', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('byClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.majorclub')),
            ],
        ),
    ]
